# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main
- develop
- features/*
- feature/*

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  BuildConfiguration: 'Release'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

    

stages:
- stage: BuildFrpsDocker
  displayName: Build Sync Docker
  dependsOn: 

  jobs:
  - job: BuildFrpsDocker
    displayName: Build frps image
    pool:
      vmImage: $(vmImageName)
    
    steps:
    - checkout: self
      submodules: true
    - task: Docker@2
      displayName: Login to docker
      inputs:
        command: login
        containerRegistry: DockerHub
    - task: Docker@2
      inputs:
        repository: automaticacore/frps
        command: 'buildAndPush'
        Dockerfile: 'docker/frps/Dockerfile'
        tags: '$(Build.BuildNumber)'
        buildContext: "$(Build.SourcesDirectory)"
        
- stage: PackageTerraform
  displayName: Pack terraform
  dependsOn: BuildFrpsDocker

  jobs:
  - job: Pack
    displayName: Pack terraform
    pool:
      vmImage: $(vmImageName)

    steps:
    - checkout: self
      submodules: true

    - task: CopyFiles@2
      inputs:
          SourceFolder: '$(Build.SourcesDirectory)/terraform'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
          CleanTargetFolder: true
          OverWrite: true

    - task: PublishBuildArtifacts@1
      inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'terraform'
          publishLocation: 'Container'