/**
 * Automatica.Core.Cloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from './user';
import { Version } from './version';


export interface CoreServerVersion {
    objId?: string;
    version?: string;
    versionObj?: Version;
    azureUrl?: string;
    azureFileName?: string;
    changeLog?: string;
    this2User?: string;
    isPrerelease?: boolean;
    isPublic?: boolean;
    rid?: string;
    this2UserNavigation?: User;
    isNewObject?: boolean;
}
