/**
 * Automatica.Core.Cloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from './user';
import { Version } from './version';


export interface CoreServer { 
    objId?: string;
    serverGuid?: string;
    serverName?: string;
    lastKnownConnection?: Date;
    lastKnownNgrokUrl?: string;
    lastKnownNgrokUrlDate?: Date;
    version?: string;
    readonly versionObj?: Version;
    rid?: string;
    apiKey?: string;
    this2User?: string;
    this2UserNavigation?: User;
    isNewObject?: boolean;
}
