/**
 * Automatica.Core.Cloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface GenerateLicenseData { 
    objId?: string;
    expiresAt: Date;
    maxDatapoints?: number;
    maxUsers?: number;
    licensedTo?: string;
    email?: string;
    this2CoreServer?: string;
    allowRemoteControl?: boolean;
    maxRemoteTunnels?: number;
    maxRecordingDataPoints?: number;
    maxSatellites?: number;
    allowTextToSpeech?: boolean;
    features?: Array<string>;
}
