/**
 * Automatica.Core.Cloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Version } from './version';


export interface ServerDockerVersion { 
    objId?: string;
    version?: string;
    readonly versionObj?: Version;
    imageName?: string;
    imageTag?: string;
    changeLog?: string;
    isPreRelease?: boolean;
    isPublic?: boolean;
    rid?: string;
    isNewObject?: boolean;
    branch?: string;
}
