/**
 * Automatica.Core.Cloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface User { 
    objId?: string;
    userName?: string;
    email?: string;
    publisherName?: string;
    passwordHash?: string;
    salt?: string;
    firstName?: string;
    lastName?: string;
    enabled?: boolean;
    activationCode?: string;
    userRole?: User.UserRoleEnum;
    apiKey?: string;
    token?: string;
}
export namespace User {
    export type UserRoleEnum = 0 | 1 | 2 | 3 | 4;
    export const UserRoleEnum = {
        NUMBER_0: 0 as UserRoleEnum,
        NUMBER_1: 1 as UserRoleEnum,
        NUMBER_2: 2 as UserRoleEnum,
        NUMBER_3: 3 as UserRoleEnum,
        NUMBER_4: 4 as UserRoleEnum
    };
}
