/**
 * Automatica.Core.Cloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { EmailData } from '../model/emailData';
import { Plugin } from '../model/plugin';
import { SayHelloData } from '../model/sayHelloData';
import { ServerVersion } from '../model/serverVersion';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class CoreServerDataService {

    protected basePath = 'https://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param rid 
     * @param coreServerVersion 
     * @param version 
     * @param apiKey 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public checkForUpdates(rid: string, coreServerVersion: string, version: string, apiKey: string, observe?: 'body', reportProgress?: boolean): Observable<ServerVersion>;
    public checkForUpdates(rid: string, coreServerVersion: string, version: string, apiKey: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ServerVersion>>;
    public checkForUpdates(rid: string, coreServerVersion: string, version: string, apiKey: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ServerVersion>>;
    public checkForUpdates(rid: string, coreServerVersion: string, version: string, apiKey: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (rid === null || rid === undefined) {
            throw new Error('Required parameter rid was null or undefined when calling checkForUpdates.');
        }

        if (coreServerVersion === null || coreServerVersion === undefined) {
            throw new Error('Required parameter coreServerVersion was null or undefined when calling checkForUpdates.');
        }

        if (version === null || version === undefined) {
            throw new Error('Required parameter version was null or undefined when calling checkForUpdates.');
        }

        if (apiKey === null || apiKey === undefined) {
            throw new Error('Required parameter apiKey was null or undefined when calling checkForUpdates.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<ServerVersion>(`${this.basePath}/v${encodeURIComponent(String(version))}/coreServerData/checkForUpdates/${encodeURIComponent(String(rid))}/${encodeURIComponent(String(coreServerVersion))}/${encodeURIComponent(String(apiKey))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param version 
     * @param apiKey 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public checkLicense(version: string, apiKey: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public checkLicense(version: string, apiKey: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public checkLicense(version: string, apiKey: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public checkLicense(version: string, apiKey: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (version === null || version === undefined) {
            throw new Error('Required parameter version was null or undefined when calling checkLicense.');
        }

        if (apiKey === null || apiKey === undefined) {
            throw new Error('Required parameter apiKey was null or undefined when calling checkLicense.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<string>(`${this.basePath}/v${encodeURIComponent(String(version))}/coreServerData/checkLicense/${encodeURIComponent(String(apiKey))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param coreServerVersion 
     * @param version 
     * @param apiKey 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAvailablePlugins(coreServerVersion: string, version: string, apiKey: string, observe?: 'body', reportProgress?: boolean): Observable<Array<Plugin>>;
    public getAvailablePlugins(coreServerVersion: string, version: string, apiKey: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Plugin>>>;
    public getAvailablePlugins(coreServerVersion: string, version: string, apiKey: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Plugin>>>;
    public getAvailablePlugins(coreServerVersion: string, version: string, apiKey: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (coreServerVersion === null || coreServerVersion === undefined) {
            throw new Error('Required parameter coreServerVersion was null or undefined when calling getAvailablePlugins.');
        }

        if (version === null || version === undefined) {
            throw new Error('Required parameter version was null or undefined when calling getAvailablePlugins.');
        }

        if (apiKey === null || apiKey === undefined) {
            throw new Error('Required parameter apiKey was null or undefined when calling getAvailablePlugins.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<Plugin>>(`${this.basePath}/v${encodeURIComponent(String(version))}/coreServerData/plugins/${encodeURIComponent(String(coreServerVersion))}/${encodeURIComponent(String(apiKey))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param version 
     * @param apiKey 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public ping(version: string, apiKey: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public ping(version: string, apiKey: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public ping(version: string, apiKey: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public ping(version: string, apiKey: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (version === null || version === undefined) {
            throw new Error('Required parameter version was null or undefined when calling ping.');
        }

        if (apiKey === null || apiKey === undefined) {
            throw new Error('Required parameter apiKey was null or undefined when calling ping.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<string>(`${this.basePath}/v${encodeURIComponent(String(version))}/coreServerData/ping/${encodeURIComponent(String(apiKey))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param apiKey 
     * @param version 
     * @param sayHelloData 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public sayHello(apiKey: string, version: string, sayHelloData?: SayHelloData, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public sayHello(apiKey: string, version: string, sayHelloData?: SayHelloData, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public sayHello(apiKey: string, version: string, sayHelloData?: SayHelloData, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public sayHello(apiKey: string, version: string, sayHelloData?: SayHelloData, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (apiKey === null || apiKey === undefined) {
            throw new Error('Required parameter apiKey was null or undefined when calling sayHello.');
        }

        if (version === null || version === undefined) {
            throw new Error('Required parameter version was null or undefined when calling sayHello.');
        }


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json',
            'application/xml',
            'text/xml',
            'application/_*+xml'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/v${encodeURIComponent(String(version))}/coreServerData/sayHello/${encodeURIComponent(String(apiKey))}`,
            sayHelloData,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param apiKey 
     * @param version 
     * @param emailData 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public sendMail(apiKey: string, version: string, emailData?: EmailData, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public sendMail(apiKey: string, version: string, emailData?: EmailData, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public sendMail(apiKey: string, version: string, emailData?: EmailData, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public sendMail(apiKey: string, version: string, emailData?: EmailData, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (apiKey === null || apiKey === undefined) {
            throw new Error('Required parameter apiKey was null or undefined when calling sendMail.');
        }

        if (version === null || version === undefined) {
            throw new Error('Required parameter version was null or undefined when calling sendMail.');
        }


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<string>(`${this.basePath}/v${encodeURIComponent(String(version))}/coreServerData/sendMail/${encodeURIComponent(String(apiKey))}`,
            emailData,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
